### ISSUE TITLE
i dont understend

### ISSUE THREAD

**Issue by kracken216765** [Lord-of-the-Galaxy/RSSBot#3]
hi can u help me for configure the bot i don't understend what i do

**Comment by kracken216765** [comment]
I'm really bad at this field so could you help me understand a bit how to set the various settings

**Comment by Lord-of-the-Galaxy** [comment]
@kracken216765 this version of the bot is probably broken, you'd have better luck with the rewrite: https://github.com/Lord-of-the-Galaxy/RSSBot/tree/rewrite
But in all likelihood even that may not work properly as it was written for a much older version of both discord.py and the discord API. If what you want is to have a bot for RSS feeds in your discord server, check out something like https://monitorss.xyz/ instead - it's an existing and well supported bot that you can just invite to your server to use. It probably has good tutorials available online as well. If you are instead looking to develop and host a bot on your own instead, then I suppose you can try to go over my code instead and let me know if you need any further help, but this will require at least some basic knowledge of python, discord.py, and the RSS web feed format.

**Comment by kracken216765** [comment]
oh ty anyway
